M48
; DRILL file {KiCad 9.0.0} date 2025-04-24T02:32:48+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-24T02:32:48+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X109.0Y-105.5
X116.0Y-40.5
X190.5Y-44.0
X193.0Y-100.0
M30
